name: "École de danse Moioli"
description: "L'école de danse Solange et Serge Moioli vous propose d'apprendre les danses  deux (cours de Rock, Salsa, Valse, etc...) dans un cadre agréable et une ambiance amicale près de Chambéry et Savoie."
keywords: "école de danse, cours de danse, ecole, école, danser, danse, chambéry, chambery, la motte servolex, aix-les-bains, Savoie, 73, moioli, cours, leçon, solange, serge, rock, salsa, valse, tango, couple, salon, societe, adulte"

baseurl: ""



paginate: 10



markdown: kramdown
permalink: pretty

exclude:
  - bootstrap-4.5.0
  - design
  - vimrc
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docker-compose.yml
include: ['.htaccess']

danses: 
  - 
    title: Rock'n roll
    name: rock
  - 
    title: Salsa cubaine
    name: salsa
  - 
    title: Lindy Hop
    name: lindy
  - 
    title: Tango Argentin
    name: tango
  - 
    title: Danses de salon
    name: salon
  - 
    title: Bachata
    name: bachata
  - 
    title: West Coast Swing
    name: westcoastswing
  - 
    title: Kizomba
    name: kizomba
  - 
    title: Solo Swing
    name: soloswing
  - 
    title: Solo Latino
    name: sololatino
