name: "École de danse Moioli"
description: "L'école de danse Solange et Serge Moioli vous propose d'apprendre les danses  deux (cours de Rock, Salsa, Valse, etc...) dans un cadre agréable et une ambiance amicale près de Chambéry et Savoie."
keywords: "école de danse, cours de danse, ecole, école, danser, danse, chambéry, chambery, la motte servolex, aix-les-bains, Savoie, 73, moioli, cours, leçon, solange, serge, rock, salsa, valse, tango, couple, salon, societe, adulte"

baseurl: ""



paginate: 10



markdown: kramdown
permalink: pretty

exclude:
  - bootstrap
  - design
  - vimrc
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docker-compose.yml
include: ['.htaccess']

danses:
  -
    title: Rock'n'roll
    name: rock
    cours:
      - [Débutant septembre 2025, Mercredi 18h30 (1h), Salle Compay]
      - [Débutant septembre 2025, Jeudi 19h30 (1h), Salle Elvis]
      - [Intermédiaire 1, Lundi 20h (1h), Salle Pugliese]
      - [Intermédiaire 1, Jeudi 18h30 (1h), Salle Elvis]
      - [Intermédiaire 2, Mardi 21h (1h), Salle Elvis]
      - [Avancé 1, Mercredi 20h (1h), Salle Pugliese]
      - [Avancé 2, Mardi 19h (1h), Salle Compay]


  -
    title: Salsa / Bachata
    name: salsa
    cours:
      - [Débutant septembre 2025, Lundi 19h (1h), Salle Compay]
      - [Débutant septembre 2025, Mercredi 19h30 (1h), Salle Elvis]
      - [Débutant septembre 2025, Jeudi 19h (1h), Salle Pugliese]
      - [Intermédiaire 1, Lundi 21h (1h), Salle Pugliese]
      - [Intermédiaire 1, Mardi 20h (1h), Salle Compay]
      - [Intermédiaire 2, Lundi 19h (1h), Salle Elvis]
      - [Intermédiaire 2, Jeudi 20h (1h), Salle Pugliese]
      - [Intermédiaire 2, Vendredi 19h (1h), Salle Pugliese]
      - [Avancé 1, Lundi 20h (1h), Salle Elvis]
      - [Avancé 2, Lundi 21h (1h), Salle Compay]
      - [Avancé 2, Mercredi 21h (1h), Salle Compay]

  -
    title: Lindy-Hop / Balboa
    name: lindy
    cours:
      - [Débutant, Mardi 20h30 (1h30), Salle Pugliese]
      - [Intermédiaire, Jeudi 20h30 (1h30), Salle Compay]
      - [Avancé, Mercredi 19h30 (1h30), Salle Compay]

  -
    title: Tango Argentin
    name: tango
    cours:
      - [Débutant / fondamentaux, Mercredi 20h30 (1h30), Salle Elvis]
      - [Intermédiaire 1, Jeudi 20h30 (1h30), Salle Elvis]
      - [Intermédiaire 2, Lundi 18h30 (1h30), Salle Pugliese]
      - [Avancé, Mercredi 18h30 (1h30), Salle Pugliese]

  -
    title: West Coast Swing
    name: westcoastswing
    cours:
      - [Débutant septembre 2025, Mardi 21h (1h), Salle Compay]
      - [Débutant septembre 2025, Jeudi 18h30 (1h), Salle Pugliese]
      - [Intermédiaire 1, Mardi 19h30 (1h), Salle Pugliese]
      - [Intermédiaire 1, Jeudi 21h (1h), Salle Pugliese]
      - [Intermédiaire 2, Vendredi 20h (1h), Salle Pugliese]
      - [Avancé 1, Lundi 20h (1h), Salle Compay]
      - [Avancé 2, Jeudi 19h30 (1h), Salle Compay]

  -
    title: Kizomba
    name: kizomba
    cours:
      - [Débutant, Mardi 19h (1h), Salle Elvis]
      - [Intermédiaire, Mardi 20h (1h), Salle Elvis]
      - [Avancé, Vendredi 19h (1h), Salle Compay]

  -
    title: Solo Swing
    name: soloswing
    cours:
      - [Débutant / intermédiaire, Mardi 18h30 (1h), Salle Pugliese]
      - [Inter / Avancé, Mercredi 18h30 (1h), Salle Compay]

  -
    title: Blues
    name: blues
    cours:
      - [Débutant, Vendredi 20h (1h), Salle Compay]
