name: "École de danse Moioli"
description: "L'école de danse Solange et Serge Moioli vous propose d'apprendre les danses  deux (cours de Rock, Salsa, Valse, etc...) dans un cadre agréable et une ambiance amicale près de Chambéry et Savoie."
keywords: "école de danse, cours de danse, ecole, école, danser, danse, chambéry, chambery, la motte servolex, aix-les-bains, Savoie, 73, moioli, cours, leçon, solange, serge, rock, salsa, valse, tango, couple, salon, societe, adulte"

baseurl: ""



paginate: 10



markdown: kramdown
permalink: pretty

exclude:
  - bootstrap
  - design
  - vimrc
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docker-compose.yml
include: ['.htaccess']

danses:
  -
    title: Rock'n'roll
    name: rock
    cours:
      - [Débutant janvier, Mardi 20h (1h), Salle Elvis]
      - [Débutant, Mardi 21h (1h), Salle Elvis]
      - [Débutant, Mercredi 19h30 (1h), Salle Elvis]
      - [Débutant, Jeudi 18h30 (1h), Salle Compay]
      - [Intermédiaire 1, Mercredi 20h30 (1h), Salle Elvis]
      - [Intermédiaire 1, Jeudi 19h30 (1h), Salle Elvis]
      - [Intermédiaire 2, Lundi 19h (1h), Salle Elvis]
      - [Intermédiaire 2, Mercredi 20h (1h), Salle Pugliese]
      - [Avancé 1, Mardi 19h (1h), Salle Compay]
      - [Avancé 2, Jeudi 18h30 (1h), Salle Pugliese]

  -
    title: Salsa / Bachata
    name: salsa
    cours:
      - [Débutant janvier, Lundi 19h (1h), Salle Elvis]
      - [Débutant, Lundi 21h (1h), Salle Elvis]
      - [Débutant, Mardi 20h (1h), Salle Elvis]
      - [Débutant, Jeudi 19h30 (1h), Salle Pugliese]
      - [Débutant, Vendredi 19h (1h), Salle Pugliese]
      - [Intermédiaire 1, Lundi 20h (1h), Salle Elvis]
      - [Intermédiaire 1, Mardi 21h (1h), Salle Compay]
      - [Intermédiaire 1, Jeudi 18h30 (1h), Salle Elvis]
      - [Intermédiaire 2, Mercredi 21h (1h), Salle Pugliese]
      - [Intermédiaire 3, Jeudi 20h30 (1h), Salle Elvis]
      - [Intermédiaire 3, Lundi 21h (1h), Salle Compay]
      - [Avancé 1, Mercredi 21h (1h), Salle Compay]
      - [Avancé 2, Mardi 20h (1h), Salle Compay]


  -
    title: Lindy-Hop / Balboa
    name: lindy
    cours:
        - [Débutant, Jeudi 20h30 (1h), Salle Pugliese]
        - [Intermédiaire 1, Lundi 20h (1h30), Salle Pugliese]
        - [Intermédiaire 2, Mardi 20h (1h30), Salle Pugliese]
        - [Avancé, Mercredi 19h30 (1h30), Salle Compay]
  -
    title: Tango Argentin
    name: tango
    cours:
        - [Débutant, Mardi 19h (1h), Salle Elvis]
        - [Intermédiaire, Lundi 18h30 (1h30), Salle Pugliese]
        - [Avancé, Jeudi 20h30 (1h30), Salle Compay]
        - [Avancé, Mercredi 18h30 (1h30), Salle Pugliese]

  -
    title: Danses de salon
    name: salon
    cours:
        - [Inter/Avancé, Lundi 17h30 (1h), Salle Compay]
  -
    title: West Coast Swing
    name: westcoastswing
    cours:
      - [Débutant janvier, Vendredi 19h (1h), Salle Compay]
      - [Débutant, Mercredi 18h30 (1h), Salle Compay]
      - [Débutant, Vendredi 20h (1h), Salle Pugliese]
      - [Intermédiaire 1, Mardi 19h (1h), Salle Pugliese]
      - [Intermédiaire 2, Lundi 20h (1h), Salle Compay]
      - [Avancé, Jeudi 19h30 (1h), Salle Compay]
  -
    title: Kizomba
    name: kizomba
    cours:
      - [Débutant, Vendredi 20h (1h), Salle Elvis]
      - [Inter/Avancé, Vendredi 19h (1h), Salle Compay]
  -
    title: Solo Swing
    name: soloswing
    cours:
      - [Tous niveaux, Mercredi 18h30 (1h), Salle Compay]
  -
    title: Ateliers
    name: ateliers
