name: "École de danse Moioli"
description: "L'école de danse Solange et Serge Moioli vous propose d'apprendre les danses  deux (cours de Rock, Salsa, Valse, etc...) dans un cadre agréable et une ambiance amicale près de Chambéry et Savoie."
keywords: "école de danse, cours de danse, ecole, école, danser, danse, chambéry, chambery, la motte servolex, aix-les-bains, Savoie, 73, moioli, cours, leçon, solange, serge, rock, salsa, valse, tango, couple, salon, societe, adulte"

baseurl: ""



paginate: 10



markdown: kramdown
permalink: pretty

exclude:
  - bootstrap-4.5.0
  - design
  - vimrc
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docker-compose.yml
include: ['.htaccess']

danses: 
  - 
    title: Rock'n roll
    name: rock
    cours:
      - [Lundi, 21h, Salle Compay, 21 septembre 2020]
      - [Mercredi, 19h, Salle Elvis, 23 septembre 2020]
  - 
    title: Salsa cubaine
    name: salsa
    cours:
      - [Lundi, 19h, Salle Elvis, 21 septembre 2020]
      - [Mardi, 21h, Salle Elvis, 22 septembre 2020]
      - [Vendredi, 19h, Salle Pugliese, 25 septembre 2020]
  - 
    title: Lindy Hop
    name: lindy
    cours:
      - [Mardi, 19h, Salle Compay, 22 septembre 2020]
  - 
    title: Tango Argentin
    name: tango
    cours:
      - [Vendredi, 19h, Salle Elvis, 25 septembre 2020]
  - 
    title: Danses de salon
    name: salon
  - 
    title: Bachata
    name: bachata
  - 
    title: West Coast Swing
    name: westcoastswing
    cours:
      - [Lundi, 20h, Salle Elvis, 21 septembre 2020]
  - 
    title: Kizomba
    name: kizomba
    cours:
      - [Jeudi, 21h, Salle Elvis, 24 septembre 2020]
  - 
    title: Solo Swing
    name: soloswing
    cours:
      - [Mardi, 19h, Salle Elvis, 1er septembre 2020]
  - 
    title: Solo Latino
    name: sololatino
    cours:
      - [Mercredi, 20h, Salle Elvis, 02 septembre 2020]
